# Workflow to build the development Docker image
name: Periodic Docker build

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to open pull requests with changes to the Spack or Docker configuration
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - docker/Dockerfile.devenv
      - spack.yaml

  # Triggers the workflow at 00:00 on the first day of every 3 months
  schedule:
    - cron: '0 0 1 */3 *'

# Cancel jobs running if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Workflow run - one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "docker"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout FTorch repository
        with:
          persist-credentials: true
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  # v3

      - name: Log into ghcr
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and push Docker container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6
        with:
          push: true
          file: docker/Dockerfile.devenv
          tags: ghcr.io/cambridge-iccs/ftorch-dev-env:latest
